// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcdzW1mol5n-byL64mHy3f6ljMrm1JPzQ',
    appId: '1:340885578158:web:b19196097513bc07f6683f',
    messagingSenderId: '340885578158',
    projectId: 'rubber-2c39a',
    authDomain: 'rubber-2c39a.firebaseapp.com',
    storageBucket: 'rubber-2c39a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbExqdl7ikNiQU4FNI1eqrrvTzWOHDXzg',
    appId: '1:340885578158:android:9dadd48214015f9df6683f',
    messagingSenderId: '340885578158',
    projectId: 'rubber-2c39a',
    storageBucket: 'rubber-2c39a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmMHrHqUPCMqop0P-QPryMSbom7cXZc0Y',
    appId: '1:340885578158:ios:083b6b03ba140c62f6683f',
    messagingSenderId: '340885578158',
    projectId: 'rubber-2c39a',
    storageBucket: 'rubber-2c39a.firebasestorage.app',
    iosBundleId: 'com.example.rubberVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmMHrHqUPCMqop0P-QPryMSbom7cXZc0Y',
    appId: '1:340885578158:ios:083b6b03ba140c62f6683f',
    messagingSenderId: '340885578158',
    projectId: 'rubber-2c39a',
    storageBucket: 'rubber-2c39a.firebasestorage.app',
    iosBundleId: 'com.example.rubberVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcdzW1mol5n-byL64mHy3f6ljMrm1JPzQ',
    appId: '1:340885578158:web:9d47df0520263bb5f6683f',
    messagingSenderId: '340885578158',
    projectId: 'rubber-2c39a',
    authDomain: 'rubber-2c39a.firebaseapp.com',
    storageBucket: 'rubber-2c39a.firebasestorage.app',
  );
}
